"""Test fixtures based on real Open-Meteo API responses.

These fixtures were captured from actual API calls on 2025-12-14
to ensure the test data structure matches the real API.
"""

# Geocoding API response for "Berlin"
GEOCODE_BERLIN_RESPONSE = {
    "results": [
        {
            "id": 2950159,
            "name": "Berlin",
            "latitude": 52.52437,
            "longitude": 13.41053,
            "elevation": 74.0,
            "feature_code": "PPLC",
            "country_code": "DE",
            "admin1_id": 2950157,
            "admin3_id": 6547383,
            "admin4_id": 6547539,
            "timezone": "Europe/Berlin",
            "population": 3426354,
            "postcodes": ["10967", "13347"],
            "country_id": 2921044,
            "country": "Germany",
            "admin1": "State of Berlin",
            "admin3": "Berlin, Stadt",
            "admin4": "Berlin",
        },
        {
            "id": 5083330,
            "name": "Berlin",
            "latitude": 44.46867,
            "longitude": -71.18508,
            "elevation": 311.0,
            "feature_code": "PPL",
            "country_code": "US",
            "admin1_id": 5090174,
            "admin2_id": 5084973,
            "admin3_id": 5083340,
            "timezone": "America/New_York",
            "population": 9367,
            "postcodes": ["03570"],
            "country_id": 6252001,
            "country": "United States",
            "admin1": "New Hampshire",
            "admin2": "Coos",
            "admin3": "City of Berlin",
        },
    ],
    "generationtime_ms": 0.62191486,
}

# Geocoding API response for non-existent location
GEOCODE_EMPTY_RESPONSE = {"generationtime_ms": 0.23901463}

# Current weather response (metric units)
CURRENT_WEATHER_METRIC_RESPONSE = {
    "latitude": 52.52,
    "longitude": 13.419998,
    "generationtime_ms": 0.13458728790283203,
    "utc_offset_seconds": 3600,
    "timezone": "Europe/Berlin",
    "timezone_abbreviation": "GMT+1",
    "elevation": 46.0,
    "current_units": {
        "time": "iso8601",
        "interval": "seconds",
        "temperature_2m": "°C",
        "relative_humidity_2m": "%",
        "apparent_temperature": "°C",
        "weather_code": "wmo code",
        "wind_speed_10m": "km/h",
        "wind_direction_10m": "°",
        "pressure_msl": "hPa",
    },
    "current": {
        "time": "2025-12-14T12:45",
        "interval": 900,
        "temperature_2m": 5.9,
        "relative_humidity_2m": 82,
        "apparent_temperature": 2.7,
        "weather_code": 2,
        "wind_speed_10m": 11.0,
        "wind_direction_10m": 221,
        "pressure_msl": 1025.5,
    },
}

# Current weather response (imperial units)
CURRENT_WEATHER_IMPERIAL_RESPONSE = {
    "latitude": 52.52,
    "longitude": 13.419998,
    "generationtime_ms": 0.11813640594482422,
    "utc_offset_seconds": 3600,
    "timezone": "Europe/Berlin",
    "timezone_abbreviation": "GMT+1",
    "elevation": 46.0,
    "current_units": {
        "time": "iso8601",
        "interval": "seconds",
        "temperature_2m": "°F",
        "relative_humidity_2m": "%",
        "apparent_temperature": "°F",
        "weather_code": "wmo code",
        "wind_speed_10m": "mp/h",
        "wind_direction_10m": "°",
        "pressure_msl": "hPa",
    },
    "current": {
        "time": "2025-12-14T12:45",
        "interval": 900,
        "temperature_2m": 42.6,
        "relative_humidity_2m": 82,
        "apparent_temperature": 36.9,
        "weather_code": 2,
        "wind_speed_10m": 6.8,
        "wind_direction_10m": 221,
        "pressure_msl": 1025.5,
    },
}

# Daily forecast response
FORECAST_DAILY_RESPONSE = {
    "latitude": 52.52,
    "longitude": 13.419998,
    "generationtime_ms": 0.49877166748046875,
    "utc_offset_seconds": 3600,
    "timezone": "Europe/Berlin",
    "timezone_abbreviation": "GMT+1",
    "elevation": 46.0,
    "daily_units": {
        "time": "iso8601",
        "temperature_2m_max": "°C",
        "temperature_2m_min": "°C",
        "apparent_temperature_max": "°C",
        "apparent_temperature_min": "°C",
        "precipitation_sum": "mm",
        "precipitation_probability_max": "%",
        "weather_code": "wmo code",
        "sunrise": "iso8601",
        "sunset": "iso8601",
        "wind_speed_10m_max": "km/h",
    },
    "daily": {
        "time": [
            "2025-12-14",
            "2025-12-15",
            "2025-12-16",
        ],
        "temperature_2m_max": [7.2, 7.1, 6.1],
        "temperature_2m_min": [4.6, 3.7, 1.0],
        "apparent_temperature_max": [4.6, 4.0, 3.4],
        "apparent_temperature_min": [1.6, 0.6, -1.9],
        "precipitation_sum": [0.0, 0.0, 0.0],
        "precipitation_probability_max": [0, 0, 0],
        "weather_code": [3, 3, 3],
        "sunrise": [
            "2025-12-14T08:10",
            "2025-12-15T08:10",
            "2025-12-16T08:11",
        ],
        "sunset": [
            "2025-12-14T15:51",
            "2025-12-15T15:52",
            "2025-12-16T15:52",
        ],
        "wind_speed_10m_max": [12.1, 12.1, 8.3],
    },
}

# Forecast with hourly data response
FORECAST_HOURLY_RESPONSE = {
    "latitude": 52.52,
    "longitude": 13.419998,
    "generationtime_ms": 0.5,
    "utc_offset_seconds": 3600,
    "timezone": "Europe/Berlin",
    "timezone_abbreviation": "GMT+1",
    "elevation": 46.0,
    "daily_units": {
        "time": "iso8601",
        "temperature_2m_max": "°C",
        "temperature_2m_min": "°C",
        "apparent_temperature_max": "°C",
        "apparent_temperature_min": "°C",
        "precipitation_sum": "mm",
        "precipitation_probability_max": "%",
        "weather_code": "wmo code",
        "sunrise": "iso8601",
        "sunset": "iso8601",
        "wind_speed_10m_max": "km/h",
    },
    "daily": {
        "time": ["2025-12-14"],
        "temperature_2m_max": [7.2],
        "temperature_2m_min": [4.6],
        "apparent_temperature_max": [4.6],
        "apparent_temperature_min": [1.6],
        "precipitation_sum": [0.0],
        "precipitation_probability_max": [0],
        "weather_code": [3],
        "sunrise": ["2025-12-14T08:10"],
        "sunset": ["2025-12-14T15:51"],
        "wind_speed_10m_max": [12.1],
    },
    "hourly_units": {
        "time": "iso8601",
        "temperature_2m": "°C",
        "precipitation_probability": "%",
        "weather_code": "wmo code",
        "wind_speed_10m": "km/h",
    },
    "hourly": {
        "time": [
            "2025-12-14T00:00",
            "2025-12-14T01:00",
            "2025-12-14T02:00",
        ],
        "temperature_2m": [5.5, 5.3, 5.1],
        "precipitation_probability": [0, 0, 0],
        "weather_code": [3, 3, 3],
        "wind_speed_10m": [10.5, 10.2, 9.8],
    },
}

# Air quality response (without pollen)
AIR_QUALITY_RESPONSE = {
    "latitude": 52.5,
    "longitude": 13.400002,
    "generationtime_ms": 0.2638101577758789,
    "utc_offset_seconds": 3600,
    "timezone": "Europe/Berlin",
    "timezone_abbreviation": "GMT+1",
    "elevation": 46.0,
    "current_units": {
        "time": "iso8601",
        "interval": "seconds",
        "us_aqi": "USAQI",
        "european_aqi": "EAQI",
        "pm10": "μg/m³",
        "pm2_5": "μg/m³",
        "carbon_monoxide": "μg/m³",
        "nitrogen_dioxide": "μg/m³",
        "sulphur_dioxide": "μg/m³",
        "ozone": "μg/m³",
    },
    "current": {
        "time": "2025-12-14T12:00",
        "interval": 3600,
        "us_aqi": 57,
        "european_aqi": 31,
        "pm10": 15.4,
        "pm2_5": 13.6,
        "carbon_monoxide": 199.0,
        "nitrogen_dioxide": 12.3,
        "sulphur_dioxide": 2.1,
        "ozone": 35.0,
    },
}

# Air quality response (with pollen)
AIR_QUALITY_POLLEN_RESPONSE = {
    "latitude": 52.5,
    "longitude": 13.400002,
    "generationtime_ms": 0.39005279541015625,
    "utc_offset_seconds": 3600,
    "timezone": "Europe/Berlin",
    "timezone_abbreviation": "GMT+1",
    "elevation": 46.0,
    "current_units": {
        "time": "iso8601",
        "interval": "seconds",
        "us_aqi": "USAQI",
        "european_aqi": "EAQI",
        "pm10": "μg/m³",
        "pm2_5": "μg/m³",
        "carbon_monoxide": "μg/m³",
        "nitrogen_dioxide": "μg/m³",
        "sulphur_dioxide": "μg/m³",
        "ozone": "μg/m³",
        "alder_pollen": "grains/m³",
        "birch_pollen": "grains/m³",
        "grass_pollen": "grains/m³",
        "mugwort_pollen": "grains/m³",
        "olive_pollen": "grains/m³",
        "ragweed_pollen": "grains/m³",
    },
    "current": {
        "time": "2025-12-14T12:00",
        "interval": 3600,
        "us_aqi": 57,
        "european_aqi": 31,
        "pm10": 15.4,
        "pm2_5": 13.6,
        "carbon_monoxide": 199.0,
        "nitrogen_dioxide": 12.3,
        "sulphur_dioxide": 2.1,
        "ozone": 35.0,
        "alder_pollen": 0.0,
        "birch_pollen": 0.0,
        "grass_pollen": 0.0,
        "mugwort_pollen": 0.0,
        "olive_pollen": 0.0,
        "ragweed_pollen": 0.0,
    },
}
